### ISSUE TITLE
Incompatible with QGIS 2

### ISSUE THREAD

**Issue by wvierber** [rkistner/chinese-postman#2]
Can this plugin be made compatible?

**Comment by rkistner** [comment]
The amount of QGIS-specific code is quite small (see https://github.com/rkistner/chinese-postman/blob/master/chinesepostman.py), so it should not be too difficult to do. That said, I haven't worked with QGIS in the last 2 years, and I have no idea what actually needs to change.

**Comment by peternowee** [comment]
See my pull requests rkistner/chinese-postman#3 and rkistner/chinese-postman#4. The first one changes the plugin metadata to allow it to be loaded under QGIS 2.x and the second one prevents a runtime error that might be related to the move from QGIS 1.x to 2.x.

Tested with QGIS 2.8.3 on Debian (package qgis 2.8.3+dfsg-3~bpo8+1).

**Comment by rkistner** [comment]
Thanks!

**Comment by peternowee** [comment]
No problem, thank you for creating this plugin, it's very useful!

**Comment by wvierber** [comment]
Thanks both of you!

**Comment by wvierber** [comment]
Should [QGIS Python Plugins Repository](https://plugins.qgis.org/plugins/chinesepostman/) be updated?
I'm not familiar enough with QGIS to do so.

**Comment by rkistner** [comment]
I did submit an update, just waiting for approval.
