### ISSUE TITLE
icon.png

### ISSUE THREAD

**Issue by napo** [rkistner/chinese-postman#6]
I can't find the file "icon.png" used by the script install.sh included from the file resources.qrc

**Comment by rkistner** [comment]
I can confirm it's missing from the repo (I don't have any icon yet), but the plugin should work regardless.

I do see that the current install script installs to the folder for QGIS 1.x instead of 2.x though.

**Comment by napo** [comment]
If try to install the plugin in qgis 2.8, the system answers me that i need the package "resources"
![qgis_postman](https://cloud.githubusercontent.com/assets/69814/11368132/40c6b386-92b8-11e5-946f-d221ed2a8d04.png)

**Comment by rkistner** [comment]
Fixed in 0.2.1, currently waiting for approval.

**Comment by rkistner** [comment]
0.2.1 is now available via the plugin manager.
