### ISSUE TITLE
Windy Chinese Postman

### ISSUE THREAD

**Issue by mconnor27** [rkistner/chinese-postman#9]
Just an idea...  Would be cool to implement the "Windy" version of this problem - "solve the problem on a graph where the weight of an edge depends on the direction along which it is traveled".  This is highly analogous to GIS applications where terrain is a factor rather than just distance.  The weight in each direction could represent total elevation gain in that direction, or perhaps total gain per km.

Furthermore, as far as I can tell, there is no working implementation of this on the entire internet - only academic papers discussing algorithms.  Once I get a little more free time I was going to take a crack at it, but I'm not truly a programmer, graph theory expert, or QGis power-user (see other open issue....).  Perhaps with enough time and effort I can do it or at least help however.

**Comment by mconnor27** [comment]
Possibly useful resources:

https://grass.osgeo.org/grass70/manuals/r.walk.html
http://gis.stackexchange.com/questions/4551/how-to-calculate-difference-in-altitude-along-lines-using-grass

[1-s2.0-0305054894900795-main.pdf](https://github.com/rkistner/chinese-postman/files/90922/1-s2.0-0305054894900795-main.pdf)

**Comment by rkistner** [comment]
Sounds like in interesting problem, but currently out of scope of this project.
